[package]
name = "ecommerce-integration"
version = "0.1.0"
authors = ["Mohamed Abdelbary"]
edition = "2018"


[workspace]
members = [
    "export",
    "db",
    "graphql"
]

[[bin]]
name = "export"
path = "export/src/main.rs"

[dependencies]
