[package]
name = "db"
version = "0.1.0"
authors = ["Mohamed Abdelbary"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deadpool-postgres = "0.9.0"